version: "3.9"
services:
  frontend:
    image: 808790164949.dkr.ecr.us-east-1.amazonaws.com/frontend:0.0.14
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - login
      - users
      - todo
  login:
    image: 808790164949.dkr.ecr.us-east-1.amazonaws.com/login:0.0.11
    container_name: login
    depends_on:
      - users

  users:
    image: 808790164949.dkr.ecr.us-east-1.amazonaws.com/users:0.0.12
    container_name: users

  todo:
    image: 808790164949.dkr.ecr.us-east-1.amazonaws.com/todo:0.0.14
    restart: on-failure
    container_name: todo
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis